---
- name: ğŸ“š Add Golang backports PPA
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
  become: true
  notify: Update apt cache

- name: ğŸ‹ Install Golang {{ golang_version }}
  apt:
    name: "golang-{{ golang_version }}"
    state: present
  become: true
