---
- name: ğŸ“š Add Golang backports PPA
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
    update_cache: yes
  become: true

- name: ğŸ‹ Install Golang {{ golang_version }}
  package:
    name: "golang-{{ golang_version }}"
    state: present
  become: true
