---
- name: ðŸ’¾ Install autorandr
  apt:
    name: autorandr
    state: present
  become: true
  tags: autorandr

- name: ðŸ”— Link autorandr config directory
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ lookup('env', 'HOME') }}/.config/autorandr"
    state: link
    force: no
  tags: [autorandr, config]
