---
- name: Install programming languages
  hosts: localhost
  become: false
  gather_facts: false

  roles:
    # Programming languages
    - { role: ruby, tags: [ruby, dev, languages] }
    - { role: golang, tags: [go, dev, languages] }
